### ISSUE TITLE
+18 content from Odysee not filtered 

### ISSUE THREAD

**Issue by keikari** [futo-org/grayjay-plugin-odysee#1]
I'm able to view Odysee content which is tagged as "mature" on GrayJay. On Odysee these are being hidden.

For example the content from this channel can be viewed on GrayJay
https://odysee.com/@SweetieFox:3

Odysee uses `not_tags` param in the `claim_search` to filter mature content. Here is link to the tags used for filtering:
https://github.com/OdyseeTeam/odysee-frontend/blob/de3874153398dab0dc2f4be5d44794602139250b/ui/constants/tags.js#L73

**Comment by kaidelorenzo** [comment]
Newly released version 40 sends not_tags by default

**Comment by support-grayjay** [comment]
Closing issue since it's been fixed in the version 40. If you still encounter this issue feel free to reopen it. Also, thank you for reporting this :)
